const LOAD_USER = "LOAD_USER";
const LOAD_MOST_POPULAR_COLLECTION = "LOAD_MOST_POPULAR_COLLECTION";
const LOAD_SEARCHABLE_COLLECTION = "LOAD_SEARCHABLE_COLLECTION";
const LOAD_MARKETPLACE_NFT = "LOAD_MARKETPLACE_NFT";
const LOAD_NFT_DETAIL = "LOAD_NFT_DETAILS";
const LOAD_ACCOUNT_DATA = "LOAD_ACCOUNT_DATA";


// CREATE AUCTION
const LOAD_CREATE_AUCTION = 'LOAD_CREATE_AUCTION';

export  {
    LOAD_USER,
    LOAD_MOST_POPULAR_COLLECTION,
    LOAD_SEARCHABLE_COLLECTION,
    LOAD_MARKETPLACE_NFT,
    LOAD_NFT_DETAIL,
    LOAD_ACCOUNT_DATA,
    LOAD_CREATE_AUCTION
};