const LOAD_USER = "LOAD_USER";
const LOAD_MOST_POPULAR_COLLECTION = "LOAD_MOST_POPULAR_COLLECTION";
const LOAD_SEARCHABLE_COLLECTION = "LOAD_SEARCHABLE_COLLECTION";

export  {
    LOAD_USER,
    LOAD_MOST_POPULAR_COLLECTION,
    LOAD_SEARCHABLE_COLLECTION
};