const LOAD_USER = "LOAD_USER";

const IMPORT_COLLECTION = "IMPORT_COLLECTION";

const LOAD_MOST_POPULAR_COLLECTION = "LOAD_MOST_POPULAR_COLLECTION";
const LOAD_SEARCHABLE_COLLECTION = "LOAD_SEARCHABLE_COLLECTION";
const LOAD_MARKETPLACE_NFT = "LOAD_MARKETPLACE_NFT";

const LOAD_MARKET_PLACE= "LOAD_MARKET_PLACE";


const LOAD_COLLECTION = "LOAD_COLLECTION";
const LOAD_COLLECTION_NFTS = "LOAD_COLLECTION_NFTS";
const UPDATE_COLLECTION = "UPDATE_COLLECTION";

const LOAD_NFT_DETAIL = "LOAD_NFT_DETAILS";

const LOAD_ACCOUNT_NFTS = "LOAD_ACCOUNT_NFTS";
const LOAD_ACCOUNT_COLLECTIONS = "LOAD_ACCOUNT_COLLECTIONS";

const LOAD_LISTED_NFTS = "LOAD_LISTED_NFTS";

const UPDATE_PROFILE = "UPDATE_PROFILE";

// CREATE AUCTION
const LOAD_CREATE_AUCTION = 'LOAD_CREATE_AUCTION';

export  {
    LOAD_USER,
    IMPORT_COLLECTION,
    LOAD_MOST_POPULAR_COLLECTION,
    LOAD_SEARCHABLE_COLLECTION,
    LOAD_MARKETPLACE_NFT,
    LOAD_COLLECTION,
    LOAD_COLLECTION_NFTS,
    UPDATE_COLLECTION,
    LOAD_NFT_DETAIL,
    LOAD_ACCOUNT_NFTS,
    LOAD_ACCOUNT_COLLECTIONS,
    LOAD_CREATE_AUCTION,
    LOAD_LISTED_NFTS,
    LOAD_MARKET_PLACE,
    UPDATE_PROFILE
};