name: Create, publish and deploy the fox marketplace frontend to staging environment

on:
  push:
    branches: [ 'staging/*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Release name
        id: release_name
        uses: actions/github-script@v4
        with:
          result-encoding: string
          script: |
            const branch_name = process.env.GITHUB_REF
            const staging_version = branch_name.substring(branch_name.lastIndexOf('/') +1 ,branch_name.length  )
            process.env.VERSION = staging_version
            return staging_version
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          build-args: ENVIRONMENT=.env.staging
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-staging:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-staging:v${{ steps.release_name.outputs.result }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: deploy changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_KEY }}
          port: ${{ secrets.STAGING_PORT }}
          script: |
            docker login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker-compose -f ${{ secrets.DOCKER_COMPOSE_FILE }} pull 
            docker-compose -f ${{ secrets.DOCKER_COMPOSE_FILE }} up -d frontend
            docker logout
            docker image prune -a -f
